<a href="https://colab.research.google.com/github/VishwanathPratapSingh2/SCHOLARSHIP-ELIGIBLITY-CLASSIFICATION-MODEL-ML/blob/main/Scholarship_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# --- 1. Load the data ---
df = pd.read_csv('/content/download (3).csv')

In [ ]:
df.head()

,Application ID,Entry Year,No. of times scholarship Given,Year of Scholarship given,Application Status (Fresh/Renewal),Scholars/Non Scholars,Eligible/Not Eligible,Applicant Name,Gender,Relaxation,...,Current Course (2020-21),Scholarship Amount (2020-21),Institute Location (2020-21),Cohort (2021-22),Current Course (2021-22),Last Class Actual Percentage (2021-22),Scholarship Amount (2021-22),Institute Location (2021-22),SH id (2022-23),SH id (2023-24)
0,PRIF0001,2020-21,Twice,Year 2 3,Renewal,Scholar,Eligible,aadeshbakeraopingal,Male,Meritorious GEN,...,Bachelor of Engineering,33664.0,Dindori,Professional College,Bachelor of Engineering,74.80,33664.0,Not Applicable,Not Applicable,Not Applicable
1,PRIF0012,2019-20,Twice,Year 2 3,Renewal,Scholar,Eligible,aartibhimraojadhav,Female,Female,...,Bachelor of Engineering,33664.0,Dindori,Professional College,Bachelor of Engineering,74.80,25500.0,Not Applicable,Not Applicable,Not Applicable
2,PRIF0013,2020-21,Twice,Year 2 3,Renewal,Scholar,Eligible,aartidattushinde,Female,ST,...,School,6000.0,Dindori,School,School,87.17,6000.0,Not Applicable,Not Applicable,Not Applicable
3,PRIF0024,2020-21,Once,Year 2,Fresh,Non Scholar,Not Eligible,abhijitjayavantraodeore,Male,Meritorious GEN,...,Master of Library Science,23800.0,Others,Not Applicable,Not Applicable,0.00,0.0,Not Applicable,Not Applicable,Not Applicable
4,PRIF0027,2020-21,Twice,Year 2 3,Renewal,Scholar,Eligible,abhijitsahebraobaste,Male,Meritorious GEN,...,Diploma in Mechnical,10000.0,Others,ITI/Diploma,Diploma in Mechnical,87.38,10000.0,Not Applicable,Not Applicable,Not Applicable

In [41]:
df["Scholars/Non Scholars"].value_counts()

Scholars/Non Scholars
Non Scholar    1043
Scholar         323
Name: count, dtype: int64

ASK 6 QUESTIONS

#WHAT IS THE SHAPE OF THE DATA

In [42]:
#what is the shape of the database
df.shape

(1366, 30)

In [43]:
df.isnull().sum()

Application ID                              0
Entry Year                                  0
No. of times scholarship Given              0
Year of Scholarship given                   0
Application Status (Fresh/Renewal)          0
Scholars/Non Scholars                       0
Eligible/Not Eligible                       0
Applicant Name                              0
Gender                                      0
Relaxation                                  0
Current City                                0
Age Group                                   0
Family Annual Income Range                  0
SH id (2019-20)                             0
Cohort (2019-20)                            0
Current Course  (2019-20)                   0
Last Class  Actual Percentage  (2019-20)    0
Scholarship Amount  (2019-20)               0
Institute Location (2019-20)                0
Cohort (2020-21)                            0
Current Course (2020-21)                    0
Scholarship Amount (2020-21)                0
Institute Location (2020-21)                0
Cohort (2021-22)                            0
Current Course (2021-22)                    0
Last Class Actual Percentage (2021-22)      0
Scholarship Amount (2021-22)                0
Institute Location (2021-22)                0
SH id (2022-23)                             0
SH id (2023-24)                             0
dtype: int64

In [44]:
df.duplicated().sum()

np.int64(0)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1366 entries, 0 to 1365
Data columns (total 30 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Application ID                            1366 non-null   object
 1   Entry Year                                1366 non-null   object
 2   No. of times scholarship Given            1366 non-null   object
 3   Year of Scholarship given                 1366 non-null   object
 4   Application Status (Fresh/Renewal)        1366 non-null   object
 5   Scholars/Non Scholars                     1366 non-null   object
 6   Eligible/Not Eligible                     1366 non-null   object
 7   Applicant Name                            1366 non-null   object
 8   Gender                                    1366 non-null   object
 9   Relaxation                                1366 non-null   object
 10  Current City                              1366 non-null   object
 11  Age Group                                 1366 non-null   object
 12  Family Annual Income Range                1366 non-null   object
 13  SH id (2019-20)                           1366 non-null   object
 14  Cohort (2019-20)                          1366 non-null   object
 15  Current Course  (2019-20)                 1366 non-null   object
 16  Last Class  Actual Percentage  (2019-20)  1366 non-null   float64
 17  Scholarship Amount  (2019-20)             1366 non-null   float64
 18  Institute Location (2019-20)              1366 non-null   object
 19  Cohort (2020-21)                          1366 non-null   object
 20  Current Course (2020-21)                  1366 non-null   object
 21  Scholarship Amount (2020-21)              1366 non-null   float64
 22  Institute Location (2020-21)              1366 non-null   object
 23  Cohort (2021-22)                          1366 non-null   object
 24  Current Course (2021-22)                  1366 non-null   object
 25  Last Class Actual Percentage (2021-22)    1366 non-null   float64
 26  Scholarship Amount (2021-22)              1366 non-null   float64
 27  Institute Location (2021-22)              1366 non-null   object
 28  SH id (2022-23)                           1366 non-null   object
 29  SH id (2023-24)                           1366 non-null   object
dtypes: float64(5), object(25)
memory usage: 320.3+ KB

In [46]:
df.describe()

,Last Class Actual Percentage (2019-20),Scholarship Amount (2019-20),Scholarship Amount (2020-21),Last Class Actual Percentage (2021-22),Scholarship Amount (2021-22)
count,1366.000000,1366.000000,1366.000000,1366.000000,1366.000000
mean,18.571384,3782.423133,5509.961201,21.676833,5027.037335
std,31.141594,11519.014573,13681.892860,36.048313,12934.321517
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000
75%,56.620000,6000.000000,6000.000000,66.767500,6000.000000
max,90.000000,235000.000000,161250.000000,97.400000,159873.000000

ENCODING THE TARGET VALUE

In [47]:
#from sklearn.model_selection import train_test_split
#from sklearn.preprocessing import OneHotEncoder, StandardScaler
df["Scholars/Non Scholars"] = df["Scholars/Non Scholars"].map({"Scholar": 1, "Non Scholar": 0})

FEATURE SCALING

In [48]:
#  Define target and features
target_variable = 'Scholars/Non Scholars'


features_to_exclude = [
    target_variable,
    'Application ID',
    'Applicant Name',
    'SH id (2019-20)',
    'SH id (2022-23)',
    'SH id (2023-24)',
    'Eligible/Not Eligible',
    'Scholarship Amount  (2019-20)',
    'Scholarship Amount (2020-21)',
    'Scholarship Amount (2021-22)'
]

# Create feature matrix (X) and target vector (y)
X = df.drop(columns=[col for col in features_to_exclude if col in df.columns])
y = df[target_variable]

#  Identify numerical and categorical features for preprocessing
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

SPLITTING DATA INTO TRAINING AND TEST SETS

In [50]:
# --- 5. Data Splitting ---
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [51]:
X_train.shape

(1092, 20)

In [52]:
X_test.shape

(274, 20)

CREATING PREPROCESSING PIPELINES

In [53]:

numerical_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])


preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ],
    remainder='passthrough' # Keeps any columns not specified (e.g., if there were others)
)
# Build the full pipeline with preprocessing and Logistic Regression Classifier

model_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                                 ('classifier', LogisticRegression(random_state=42, solver='liblinear', max_iter=1000))])

TRAIN THE MODEL

In [54]:

print("Training Logistic Regression Classifier...")
model_pipeline.fit(X_train, y_train)
print("Training complete.")

Training Logistic Regression Classifier...
Training complete.

In [55]:
y_pred = model_pipeline.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score, classification_report

In [57]:
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}\n")
print("Classification Report:\n", report)

Accuracy: 0.9891

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      0.99       209
           1       0.97      0.98      0.98        65

    accuracy                           0.99       274
   macro avg       0.98      0.99      0.98       274
weighted avg       0.99      0.99      0.99       274

PREDICTION SYSTEM

In [58]:

applicant = {
    'Entry Year': '2020-21',
    'No. of times scholarship Given': 'Twice',
    'Year of Scholarship given': 'Year 2 3',
    'Application Status (Fresh/Renewal)': 'Renewal',
    'Scholars/Non Scholars': '',
    'Gender': 'Female',
    'Relaxation': 'Meritorious GEN',
    'Current City': 'Dindori',
    'Age Group': '19-25 Years',
    'Family Annual Income Range': '500000-1000000',
    'Cohort (2019-20)': 'Professional College',
    'Current Course  (2019-20)': 'Bachelor of Engineering',
    'Institute Location (2019-20)': 'Dindori',
    'Cohort (2020-21)': 'Professional College',
    'Current Course (2020-21)': 'Bachelor of Engineering',
    'Institute Location (2020-21)': 'Dindori',
    'Cohort (2021-22)': 'Professional College',
    'Current Course (2021-22)': 'Bachelor of Engineering',
    'Last Class Actual Percentage (2021-22)': 90,
    'Institute Location (2021-22)': 'Dindori'
}
if applicant['Last Class Actual Percentage (2021-22)'] > 80 and \
   applicant['Application Status (Fresh/Renewal)'] == 'Renewal' and \
   applicant['Gender'] == 'Female':
    print("Scholar")
else:
    print("Non Scholar")

Scholar

In [59]:
applicant = {
    'Entry Year': '2020-21',
    'No. of times scholarship Given': '0',
    'Year of Scholarship given': '0',
    'Application Status (Fresh/Renewal)': 'Fresh',
    'Scholars/Non Scholars': '',
    'Gender': 'Male',
    'Relaxation': 'Meritorious GEN',
    'Current City': 'Dindori',
    'Age Group': '19-25 Years',
    'Family Annual Income Range': '5000000-10000000',
    'Cohort (2019-20)': 'Professional College',
    'Current Course  (2019-20)': 'Bachelor of Engineering',
    'Institute Location (2019-20)': 'Dindori',
    'Cohort (2020-21)': 'Professional College',
    'Current Course (2020-21)': 'Bachelor of Engineering',
    'Institute Location (2020-21)': 'Dindori',
    'Cohort (2021-22)': 'Professional College',
    'Current Course (2021-22)': 'Bachelor of Engineering',
    'Last Class Actual Percentage (2021-22)': 70,
    'Institute Location (2021-22)': 'Dindori'
}
if applicant['Last Class Actual Percentage (2021-22)'] > 80 and \
   applicant['Application Status (Fresh/Renewal)'] == 'Renewal' and \
   applicant['Relaxation'] == 'Female':
   print("Scholar")
else:
    print("Non Scholar")

Non Scholar